name: Build & Push wrk Multiarch Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            use_qemu: false
          - arch: arm64
            platform: linux/arm64
            use_qemu: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (only for arm64)
        if: matrix.use_qemu == true
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image (${{ matrix.arch }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            bailangvkinag/wrk:${{ matrix.arch }}

  manifest:
    name: Merge to latest
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Multiarch Manifest
        run: |
          docker manifest create bailangvkinag/wrk:latest \
            --amend bailangvkinag/wrk:amd64 \
            --amend bailangvkinag/wrk:arm64
          docker manifest push bailangvkinag/wrk:latest
