name: Build & Push wrk Multi-Arch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wrk:${{ matrix.arch }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create & Push manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/wrk:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/wrk:amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/wrk:arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/wrk:latest
