name: Build and Push wrk Multiarch Docker Image

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.multiarch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bailangvkinag/wrk:latest
            bailangvkinag/wrk:${{ github.sha }}
