name: Build & Push wrk Multi-Arch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set version timestamp
        id: set-version
        run: |
          echo "VERSION=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # bailangvvking
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub Token
    
      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build & Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wrk:amd64
            ${{ secrets.DOCKER_USERNAME }}/wrk:arm64
            ${{ secrets.DOCKER_USERNAME }}/wrk:latest
            ${{ secrets.DOCKER_USERNAME }}/wrk:${{ env.VERSION }}
