name: Build & Push wrk Multi-arch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        include:
          - arch: amd64
            platform: linux/amd64
            use_qemu: false
          - arch: arm64
            platform: linux/arm64
            use_qemu: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}    # bailangvvking
          password: ${{ secrets.DOCKER_PASSWORD }}    # dckr_pat_...

      - name: Set up QEMU (ARM only)
        if: matrix.use_qemu == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wrk:${{ matrix.arch }}

  manifest:
    name: Create & Push manifest
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/wrk:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/wrk:amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/wrk:arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/wrk:latest
